### PR TITLE
Add unicode filename

### PR DESCRIPTION
**Pull request by joshbetz**
See https://github.com/src-d/go-git/pull/526

### CODE REVIEW

**Comment by smola** [comment]
We probably need to add a new repository for that (`filenames`?), otherwise, many tests will be broken since they rely on this fixture being exactly what it is right now.

In fact, the mere fact of opening a PR here broke some tests since there is a new reference, but I guess we'll have to live with that ;)

cc @mcuadros

**Comment by mcuadros** [comment]
Since a few time all the test related with worktree aren't using fixtures. The test creates the repository on fly

**Comment by joshbetz** [comment]
> Since a few time all the test related with worktree aren't using fixtures. The test creates the repository on fly

Unfortunately I don't think it's possible to create the repository on the fly in this case because whatever platform you're on will normalize the filename when the file is created.

**Comment by mcuadros** [comment]
If you use a memfs this doesn't happens, I am changing the test on your PR

**Pull request closed without merging**
